services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vitaliidushko
      POSTGRES_PASSWORD: Vitalia1507
      POSTGRES_DB: engineer_test_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vitaliidushko -d engineer_test_db"]
      interval: 30s
      timeout: 5s
      retries: 3

  api:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: vitaliidushko
      POSTGRES_PASSWORD: Vitalia1507
      POSTGRES_DB: engineer_test_db
      POSTGRES_DB_PORT: 5432
    ports:
      - "3000:3000"

volumes:
  db_data:

